<a href="https://colab.research.google.com/github/Ayushjha02/speech-to-text/blob/main/F_speechtoText.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd
audio_file_metadata = pd.read_csv("/content/drive/MyDrive/metadata.csv")

In [6]:
audio_file_metadata.head()

,Unnamed: 0,id,sentence,file_name,audio_path
0,0,LJ001-0001,"Printing, in the only sense with which we are ...",LJ001-0001.wav,/kaggle/input/ljspeech-dataset/LJSpeech-1.1/wa...
1,1,LJ001-0002,in being comparatively modern.,LJ001-0002.wav,/kaggle/input/ljspeech-dataset/LJSpeech-1.1/wa...
2,2,LJ001-0003,For although the Chinese took impressions from...,LJ001-0003.wav,/kaggle/input/ljspeech-dataset/LJSpeech-1.1/wa...
3,3,LJ001-0004,"produced the block books, which were the immed...",LJ001-0004.wav,/kaggle/input/ljspeech-dataset/LJSpeech-1.1/wa...
4,4,LJ001-0005,the invention of movable metal letters in the ...,LJ001-0005.wav,/kaggle/input/ljspeech-dataset/LJSpeech-1.1/wa...

#**keeping required rows**

In [7]:
df = audio_file_metadata[['file_name','sentence']]
df = df.rename(columns={
    "file_name": "audio",
    "sentence": "text"
})

In [8]:
df.head()

            audio                                               text
0  LJ001-0001.wav  Printing, in the only sense with which we are ...
1  LJ001-0002.wav                     in being comparatively modern.
2  LJ001-0003.wav  For although the Chinese took impressions from...
3  LJ001-0004.wav  produced the block books, which were the immed...
4  LJ001-0005.wav  the invention of movable metal letters in the ...

In [95]:
import os
for value in df['audio']:
 audio_path = '/content/drive/MyDrive/wavs (1)/' + value
 if os.path.exists(audio_path):
  continue
 else:
  df.drop(df[df['audio'] == value].index, inplace = True)

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2160 entries, 0 to 2159
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   audio   2160 non-null   object
 1   text    2160 non-null   object
dtypes: object(2)
memory usage: 50.6+ KB

**Read file from the folder**

In [1]:
!pip install --upgrade --force-reinstall librosa

Collecting librosa
  Using cached librosa-0.11.0-py3-none-any.whl.metadata (8.7 kB)
Collecting audioread>=2.1.9 (from librosa)
  Using cached audioread-3.1.0-py3-none-any.whl.metadata (9.0 kB)
Collecting numba>=0.51.0 (from librosa)
  Using cached numba-0.65.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting numpy>=1.22.3 (from librosa)
  Using cached numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting scipy>=1.6.0 (from librosa)
  Using cached scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting scikit-learn>=1.1.0 (from librosa)
  Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting joblib>=1.0 (from librosa)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting decorator>=4.3.0 (from librosa)
  Using cached decorator-5.2.1-py3-none-any.whl.metadata (3.9 kB)
Collecting soundfile>=0.12.1 (from librosa)
  Using cached soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting pooch>=1.1 (from librosa)
  Using cached pooch-1.9.0-py3-none-any.whl.metadata (10 kB)
Collecting soxr>=0.3.2 (from librosa)
  Using cached soxr-1.1.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Collecting typing_extensions>=4.1.1 (from librosa)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting lazy_loader>=0.1 (from librosa)
  Using cached lazy_loader-0.5-py3-none-any.whl.metadata (5.9 kB)
Collecting msgpack>=1.0 (from librosa)
  Using cached msgpack-1.1.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting packaging (from lazy_loader>=0.1->librosa)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting llvmlite<0.48,>=0.47.0dev0 (from numba>=0.51.0->librosa)
  Using cached llvmlite-0.47.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Collecting platformdirs>=2.5.0 (from pooch>=1.1->librosa)
  Using cached platformdirs-4.9.6-py3-none-any.whl.metadata (4.7 kB)
Collecting requests>=2.19.0 (from pooch>=1.1->librosa)
  Using cached requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn>=1.1.0->librosa)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting cffi>=1.0 (from soundfile>=0.12.1->librosa)
  Using cached cffi-2.0.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0->soundfile>=0.12.1->librosa)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.19.0->pooch>=1.1->librosa)
  Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests>=2.19.0->pooch>=1.1->librosa)
  Using cached idna-3.13-py3-none-any.whl.metadata (8.0 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.19.0->pooch>=1.1->librosa)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests>=2.19.0->pooch>=1.1->librosa)
  Using cached certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Using cached librosa-0.11.0-py3-none-any.whl (260 kB)
Using cached audioread-3.1.0-py3-none-any.whl (23 kB)
Using cached decorator-5.2.1-py3-none-any.whl (9.2 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached lazy_loader-0.5-py3-none-any.whl (8.0 kB)
Using cached msgpack-1.1.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (427 kB)
Using cached numba-0.65.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
Using cached numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Using cached pooch-1.9.0-py3-none-any.whl (67 kB)
Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
Using cached scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
Using cached soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl (1.3 MB)
Using cached soxr-1.1.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (240 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached cffi-2.0.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (219 kB)
Using cached llvmlite-0.47.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
Using cached packaging-26.2-py3-none-any.whl (100 kB)
Using cached platformdirs-4.9.6-py3-none-any.whl (21 kB)
Using cached requests-2.33.1-py3-none-any.whl (64 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached certifi-2026.4.22-py3-none-any.whl (135 kB)
Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (216 kB)
Using cached idna-3.13-py3-none-any.whl (68 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: urllib3, typing_extensions, threadpoolctl, pycparser, platformdirs, packaging, numpy, msgpack, llvmlite, joblib, idna, decorator, charset_normalizer, certifi, audioread, soxr, scipy, requests, numba, lazy_loader, cffi, soundfile, scikit-learn, pooch, librosa
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 3.6.0
    Uninstalling threadpoolctl-3.6.0:
      Successfully uninstalled threadpoolctl-3.6.0
  Attempting uninstall: pycparser
    Found existing installation: pycparser 3.0
    Uninstalling pycparser-3.0:
      Successfully uninstalled pycparser-3.0
  Attempting uninstall: platformdirs
    Found existing installation: platformdirs 4.9.6
    Uninstalling platformdirs-4.9.6:
      Successfully uninstalled platformdirs-4.9.6
  Attempting uninstall: packaging
    Found existing installation: packaging 26.2
    Uninstalling packaging-26.2:
      Successfully uninstalled packaging-26.2
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.4
    Uninstalling numpy-2.4.4:
      Successfully uninstalled numpy-2.4.4
  Attempting uninstall: msgpack
    Found existing installation: msgpack 1.1.2
    Uninstalling msgpack-1.1.2:
      Successfully uninstalled msgpack-1.1.2
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.47.0
    Uninstalling llvmlite-0.47.0:
      Successfully uninstalled llvmlite-0.47.0
  Attempting uninstall: joblib
    Found existing installation: joblib 1.5.3
    Uninstalling joblib-1.5.3:
      Successfully uninstalled joblib-1.5.3
  Attempting uninstall: idna
    Found existing installation: idna 3.13
    Uninstalling idna-3.13:
      Successfully uninstalled idna-3.13
  Attempting uninstall: decorator
    Found existing installation: decorator 5.2.1
    Uninstalling decorator-5.2.1:
      Successfully uninstalled decorator-5.2.1
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.4.7
    Uninstalling charset-normalizer-3.4.7:
      Successfully uninstalled charset-normalizer-3.4.7
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.4.22
    Uninstalling certifi-2026.4.22:
      Successfully uninstalled certifi-2026.4.22
  Attempting uninstall: audioread
    Found existing installation: audioread 3.1.0
    Uninstalling audioread-3.1.0:
      Successfully uninstalled audioread-3.1.0
  Attempting uninstall: soxr
    Found existing installation: soxr 1.1.0
    Uninstalling soxr-1.1.0:
      Successfully uninstalled soxr-1.1.0
  Attempting uninstall: scipy
    Found existing installation: scipy 1.17.1
    Uninstalling scipy-1.17.1:
      Successfully uninstalled scipy-1.17.1
  Attempting uninstall: requests
    Found existing installation: requests 2.33.1
    Uninstalling requests-2.33.1:
      Successfully uninstalled requests-2.33.1
  Attempting uninstall: numba
    Found existing installation: numba 0.65.1
    Uninstalling numba-0.65.1:
      Successfully uninstalled numba-0.65.1
  Attempting uninstall: lazy_loader
    Found existing installation: lazy-loader 0.5
    Uninstalling lazy-loader-0.5:
      Successfully uninstalled lazy-loader-0.5
  Attempting uninstall: cffi
    Found existing installation: cffi 2.0.0
    Uninstalling cffi-2.0.0:
      Successfully uninstalled cffi-2.0.0
  Attempting uninstall: soundfile
    Found existing installation: soundfile 0.13.1
    Uninstalling soundfile-0.13.1:
      Successfully uninstalled soundfile-0.13.1
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.8.0
    Uninstalling scikit-learn-1.8.0:
      Successfully uninstalled scikit-learn-1.8.0
  Attempting uninstall: pooch
    Found existing installation: pooch 1.9.0
    Uninstalling pooch-1.9.0:
      Successfully uninstalled pooch-1.9.0
  Attempting uninstall: librosa
    Found existing installation: librosa 0.11.0
    Uninstalling librosa-0.11.0:
      Successfully uninstalled librosa-0.11.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.33.1 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.2.1 which is incompatible.
Successfully installed audioread-3.1.0 certifi-2026.4.22 cffi-2.0.0 charset_normalizer-3.4.7 decorator-5.2.1 idna-3.13 joblib-1.5.3 lazy_loader-0.5 librosa-0.11.0 llvmlite-0.47.0 msgpack-1.1.2 numba-0.65.1 numpy-2.4.4 packaging-26.2 platformdirs-4.9.6 pooch-1.9.0 pycparser-3.0 requests-2.33.1 scikit-learn-1.8.0 scipy-1.17.1 soundfile-0.13.1 soxr-1.1.0 threadpoolctl-3.6.0 typing_extensions-4.15.0 urllib3-2.7.0

In [97]:
import torch
from torch.utils.data import Dataset
import librosa
import os

In [98]:
import string

class CharTokenizer:
    def __init__(self):
        # vocabulary
        self.chars = list(string.ascii_lowercase + " '")
        self.chars.append("_")  # blank token for CTC

        self.char_to_idx = {c: i for i, c in enumerate(self.chars)}
        self.idx_to_char = {i: c for c, i in self.char_to_idx.items()}

        self.blank_idx = self.char_to_idx["_"]

    # text → tokens
    def encode(self, text):
        text = text.lower()
        return [self.char_to_idx[c] for c in text if c in self.char_to_idx]

    # tokens → text
    def decode(self, indices):
        return "".join([self.idx_to_char[i] for i in indices])

    # CTC decoding (remove duplicates + blanks)
    def ctc_decode(self, indices):
        decoded = []
        prev = None

        for i in indices:
            if i != prev and i != self.blank_idx:
                decoded.append(self.idx_to_char[i])
            prev = i

        return "".join(decoded)

In [99]:
import os

print(len(os.listdir('/content/drive/MyDrive/wavs (1)')))

2166

In [100]:
from numpy import char
import torch
from torch.utils.data import Dataset
import librosa
import numpy as np
import os
import re
from pathlib import Path



def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-z' ]", "", text)
    return text
class STTDataset(Dataset,CharTokenizer):
    def __init__(self, dataframe):
        self.df = dataframe.reset_index(drop=True)
        super().__init__()

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        audio_path = '/content/drive/MyDrive/wavs (1)/' + row["audio"]
        text = clean_text(row["text"])


        file_path = Path(audio_path)

        if file_path.exists():
            if file_path != None:
             audio, sr = librosa.load(file_path, sr=16000)

        # Convert to spectrogram
             mel = librosa.feature.melspectrogram(y=audio, sr=sr, n_mels=80)
             mel = torch.tensor(mel.T, dtype=torch.float32)


        # Encode text
            tokens = torch.tensor(self.encode(text=text), dtype=torch.long)

            return mel, tokens

In [101]:
dataset = STTDataset(df)

In [105]:
def collate_fn(batch):
    # Filter out None values from the batch
    batch = [sample for sample in batch if sample is not None]

    # If the whole batch is empty, return None
    if len(batch) == 0:
        return None

    # Separate inputs (mel spectrograms) and targets (tokens)
    mels, tokens = zip(*batch)

    # Pad mel spectrograms to the longest in the batch
    max_mel_len = max(mel.shape[0] for mel in mels)
    padded_mels = [
        torch.nn.functional.pad(mel, (0, 0, 0, max_mel_len - mel.shape[0]), 'constant', 0)
        for mel in mels
    ]
    padded_mels = torch.stack(padded_mels)

    # Pad tokens to the longest in the batch
    max_token_len = max(token.shape[0] for token in tokens)
    padded_tokens = [
        torch.nn.functional.pad(token, (0, max_token_len - token.shape[0]), 'constant', 0)
        for token in tokens
    ]
    padded_tokens = torch.stack(padded_tokens)

    # Create mel_lens and token_lens tensors for sequence lengths
    mel_lens = torch.tensor([mel.shape[0] for mel in mels], dtype=torch.long)
    token_lens = torch.tensor([token.shape[0] for token in tokens], dtype=torch.long)

    return padded_mels, padded_tokens, mel_lens, token_lens

In [113]:
from torch.utils.data import DataLoader
if dataset is not None:
 loader = DataLoader(dataset, batch_size=4, shuffle=True, collate_fn=collate_fn)

tensor([[[5.6201e-04, 2.5121e-03, 2.5035e-03,  ..., 2.1046e-06,
          1.0930e-05, 3.6760e-06],
         [1.6759e-03, 6.5834e-03, 1.1522e-02,  ..., 1.2740e-04,
          3.9420e-04, 7.6264e-05],
         [1.0693e-03, 2.4123e-03, 1.2074e-02,  ..., 6.6874e-04,
          1.5155e-03, 3.0075e-04],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[2.1238e-05, 1.9612e-04, 7.9936e-04,  ..., 2.1486e-01,
          1.8561e-01, 3.7298e-02],
         [2.0020e-05, 1.3014e-04, 1.3041e-03,  ..., 2.6041e+00,
          1.5731e+00, 4.4501e-01],
         [2.5542e-05, 5.7510e-05, 1.8425e-03,  ..., 7.7360e+00,
          3.2956e+00, 7.4210e-01],
         ...,
         [4.8903e-06, 1.6864e-04, 4.1604e-03,  ..., 7.6105e-07,
          6.6000e-07, 7.8019e-08],
         [3.5976e-06, 9.3558e-05, 1.6529e-03,  ..., 6.6774e-07,
          5.2427e-07, 9.4515e-08],
         [5.0098e-06, 3.7944e-05, 6.5852e-04,  ..., 6.5262e-07,
          3.7515e-07, 1.6620e-07]],

        [[7.9928e-05, 9.6156e-05, 4.7297e-05,  ..., 5.1073e-04,
          3.5334e-05, 4.5818e-06],
         [1.3949e-04, 3.1510e-04, 1.6580e-04,  ..., 2.5242e-03,
          2.2658e-04, 1.7468e-05],
         [1.3491e-04, 3.1680e-04, 2.0040e-04,  ..., 2.9690e-03,
          8.5707e-04, 6.4171e-05],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[9.6251e-04, 2.5358e-03, 6.9951e-02,  ..., 4.3643e-07,
          3.8340e-07, 6.1589e-08],
         [1.3517e-03, 4.2814e-03, 1.7961e-01,  ..., 4.8032e-05,
          1.2245e-03, 2.7767e-04],
         [2.6267e-04, 1.4134e-03, 7.1233e-02,  ..., 7.0451e-04,
          1.3712e-02, 3.8539e-03],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]]) tensor([[ 8,  3, 11,  4, 13,  4, 18, 18, 26, 22,  0, 18, 26, 13, 14, 19, 26, 18,
         14, 26, 20, 13,  8, 21,  4, 17, 18,  0, 11, 11, 24, 26, 19,  7,  4, 26,
         17, 20, 11,  4, 26,  8, 13, 26, 19,  7,  8, 18, 26, 15,  0, 17, 19, 26,
         14,  5, 26, 19,  7,  4, 26,  9,  0,  8, 11,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [18, 14, 26,  2, 11, 14, 18,  4, 11, 24, 26,  3,  8,  3, 26, 19,  7,  4,
         24, 26, 11,  8,  4, 26, 19, 14,  6,  4, 19,  7,  4, 17, 26, 19,  7,  0,
         19, 26, 19,  7,  4, 26,  8, 13, 18, 15,  4,  2, 19, 14, 17, 18, 26,  0,
         19, 26, 19,  7,  4,  8, 17, 26, 13,  8,  6,  7, 19, 26, 21,  8, 18,  8,
         19, 18, 26,  5, 14, 20, 13,  3, 26,  8, 19, 26,  3,  8,  5,  5,  8,  2,
         20, 11, 19, 26,  8, 13, 26, 18, 19,  4, 15, 15,  8, 13,  6, 26,  0,  2,
         17, 14, 18, 18, 26, 19,  7,  4, 26, 17, 14, 14, 12, 26, 19, 14, 26,  0,
         21, 14,  8,  3, 26, 19, 17,  4,  0,  3,  8, 13,  6, 26, 14, 13, 26, 19,
          7,  4, 12],
        [19,  7,  0, 19, 26, 15, 11,  0,  8, 13, 19,  8,  5,  5, 18, 26, 22,  4,
         17,  4, 26, 20, 13, 22,  8, 11, 11,  8, 13,  6, 26, 19, 14, 26,  2, 14,
         13, 18,  8,  6, 13, 26, 19,  7,  4, 26,  3,  4,  5,  4, 13,  3,  0, 13,
         19, 18, 26,  0,  6,  0,  8, 13, 18, 19, 26, 22,  7, 14, 12, 26, 19,  7,
          4, 24, 26,  7,  0,  3, 26, 14,  1, 19,  0,  8, 13,  4,  3, 26,  4, 23,
          4,  2, 20, 19,  8, 14, 13, 26, 19, 14, 26,  2, 14, 13,  5,  8, 13,  4,
         12,  4, 13, 19, 26, 22,  8, 19,  7,  8, 13, 26,  8, 19, 18, 26, 22,  0,
         11, 11, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [22,  4,  8,  6,  7, 19,  4,  3, 26,  1, 24, 26, 19, 17,  4,  1, 11,  4,
         26, 19,  7,  4, 26,  0, 12, 14, 20, 13, 19, 26, 14,  5, 26,  2, 14, 18,
         19, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0]])
tensor([[[2.8225e-04, 4.8324e-04, 6.0389e-03,  ..., 1.9762e-05,
          9.9149e-05, 3.4589e-05],
         [3.6663e-04, 1.0701e-03, 9.5776e-03,  ..., 4.3029e-04,
          1.6201e-03, 3.2220e-04],
         [2.1792e-04, 1.0421e-03, 6.2179e-03,  ..., 7.6327e-04,
          1.9282e-03, 3.7253e-04],
         ...,
         [1.9144e-05, 1.9762e-04, 9.5186e-04,  ..., 8.7820e-07,
          4.3706e-07, 9.8698e-08],
         [1.4637e-05, 1.0915e-04, 8.1738e-04,  ..., 8.1654e-07,
          3.9623e-07, 7.2146e-08],
         [8.6545e-06, 8.2222e-05, 2.4829e-04,  ..., 5.9149e-07,
          3.5513e-07, 6.7345e-08]],

        [[2.0899e-04, 4.7362e-04, 2.2328e-03,  ..., 2.8559e-03,
          3.5783e-03, 4.0342e-04],
         [4.8610e-04, 1.1532e-03, 9.4118e-03,  ..., 2.0707e-02,
          2.3570e-02, 3.5315e-03],
         [5.0137e-04, 1.6038e-03, 1.8045e-02,  ..., 3.6550e-02,
          4.1284e-02, 8.4153e-03],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[1.8342e-05, 8.0624e-05, 4.8355e-04,  ..., 7.7945e-04,
          1.4773e-04, 1.2408e-05],
         [1.2924e-05, 6.4485e-05, 1.0499e-03,  ..., 1.1703e-03,
          2.8673e-04, 3.7010e-05],
         [9.4419e-06, 4.8077e-05, 9.4986e-04,  ..., 5.2504e-04,
          1.4006e-04, 1.1919e-05],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[7.6178e-06, 1.3232e-05, 2.5172e-05,  ..., 7.6643e-02,
          2.5447e-02, 2.8597e-03],
         [6.2895e-06, 3.5033e-05, 1.2009e-04,  ..., 6.9524e-01,
          2.7780e-01, 2.5398e-02],
         [6.7924e-06, 4.4379e-05, 2.3134e-04,  ..., 1.6943e+00,
          7.7405e-01, 1.2304e-01],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]]) tensor([[ 1, 20, 19, 26, 19,  7,  8, 18, 26,  7,  0,  3, 26, 19,  7,  4, 26,  4,
          5,  5,  4,  2, 19, 26, 14,  5, 26, 19,  7, 17, 14, 22,  8, 13,  6, 26,
         19,  7,  4, 12, 26,  8, 13, 19, 14, 26,  2, 11, 14, 18,  4, 17, 26,  2,
         14, 13, 19,  0,  2, 19, 26,  0, 13,  3, 26, 14,  5, 26, 12,  0, 10,  8,
         13,  6, 26, 19,  7,  4, 12, 26, 12, 14, 17,  4, 26,  8, 13, 19,  8, 12,
          0, 19,  4, 11, 24, 26,  0,  2, 16, 20,  0,  8, 13, 19,  4,  3, 26, 22,
          8, 19,  7, 26, 12, 14, 17,  4, 26,  3,  8, 17,  4,  2, 19, 11, 24, 26,
          8, 13,  5, 11, 20,  4, 13, 19,  8,  0, 11, 26, 20, 15, 14, 13, 26, 14,
         13,  4, 26,  0, 13, 14, 19,  7,  4, 17],
        [19,  7,  8, 18, 26, 22, 14, 12,  0, 13, 26, 22,  0, 18, 26, 17,  4,  0,
         11, 11, 24, 26,  7,  8, 18, 26, 18,  4, 17, 21,  0, 13, 19, 26,  4, 12,
         15, 11, 14, 24,  4,  3, 26, 19, 14, 26,  7,  4, 11, 15, 26,  8, 13, 26,
          2, 11,  4,  0, 13,  8, 13,  6, 26,  0, 13,  3, 26, 19,  0, 10,  4, 13,
         26, 14, 13, 26, 22,  7,  4, 13,  4, 21,  4, 17, 26, 19,  7,  4, 17,  4,
         26, 22,  0, 18, 26,  4, 23, 19, 17,  0, 26, 22, 14, 17, 10, 26, 19, 14,
         26,  1,  4, 26,  3, 14, 13,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 5,  4,  0, 18, 19,  8, 13,  6, 26,  0, 11, 19,  4, 17, 13,  0, 19,  4,
          3, 26, 22,  8, 19,  7, 26,  5,  8,  6,  7, 19,  8, 13,  6,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [18, 14, 26, 19,  7,  0, 19, 26, 19,  7,  4, 26,  2, 20, 11, 15, 17,  8,
         19, 26,  8, 13, 26,  0,  3,  3,  8, 19,  8, 14, 13, 26, 19, 14, 26,  7,
          8, 18, 26, 18,  4, 13, 19,  4, 13,  2,  4,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])
tensor([[[1.8674e-05, 5.0704e-05, 8.2905e-05,  ..., 2.2626e-03,
          3.9673e-04, 5.8375e-05],
         [2.5986e-05, 4.8911e-05, 1.6594e-04,  ..., 3.4127e-02,
          1.2277e-02, 1.6962e-03],
         [2.5227e-05, 3.5875e-05, 3.2901e-04,  ..., 2.5373e-01,
          9.9847e-02, 9.5207e-03],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[1.1138e-04, 2.5579e-04, 4.8097e-03,  ..., 1.2062e-03,
          8.9377e-04, 9.2683e-05],
         [3.1756e-04, 5.3285e-04, 1.6153e-02,  ..., 1.9670e-02,
          1.5855e-02, 1.5938e-03],
         [1.6601e-04, 4.1698e-04, 7.2522e-02,  ..., 5.0963e-02,
          3.6786e-02, 4.4372e-03],
         ...,
         [5.9297e-06, 1.3047e-04, 3.8810e-03,  ..., 7.0147e-07,
          4.9318e-07, 8.0134e-08],
         [1.9647e-05, 6.3485e-05, 9.4709e-03,  ..., 6.5898e-07,
          4.3167e-07, 6.2193e-08],
         [7.6034e-05, 1.9544e-04, 5.8304e-03,  ..., 4.7236e-07,
          1.8916e-07, 5.1916e-08]],

        [[4.3053e-04, 5.1199e-04, 1.2889e-02,  ..., 5.0067e-04,
          1.1803e-04, 7.7681e-06],
         [1.1322e-03, 1.2837e-03, 5.2487e-02,  ..., 2.8688e-03,
          1.9133e-03, 5.1971e-04],
         [6.3179e-04, 8.8712e-04, 3.7125e-02,  ..., 1.0070e-02,
          7.1860e-03, 2.0116e-03],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[2.5183e-06, 1.3402e-05, 1.2823e-04,  ..., 1.5175e-05,
          2.9988e-05, 6.3858e-06],
         [6.5052e-06, 9.3058e-05, 4.5165e-04,  ..., 6.4308e-04,
          9.0957e-04, 1.9951e-04],
         [9.4690e-06, 6.5952e-05, 2.0001e-04,  ..., 3.2986e-03,
          4.0914e-03, 7.0435e-04],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]]) tensor([[18,  7,  4, 26, 22,  0, 18, 26, 10,  8, 11, 11,  4,  3, 26,  1, 20, 19,
         26,  8, 13, 26, 19,  7,  4, 26,  0,  2, 19, 26, 14,  5, 26,  5,  0, 11,
         11,  8, 13,  6, 26, 18,  7,  4, 26,  5, 14, 17,  2,  4,  3, 26,  7,  4,
         17, 26,  2,  7,  8, 11,  3, 26,  8, 13, 19, 14, 26, 19,  7,  4, 26,  0,
         17, 12, 18, 26, 14,  5, 26,  0, 26, 12,  0, 13, 26, 13,  4,  0, 17, 26,
          7,  4, 17, 26,  0, 13,  3, 26,  8, 12, 15, 11, 14, 17,  4,  3, 26,  7,
          8, 12, 26,  8, 13, 26,  6, 14,  3, 27, 18, 26, 13,  0, 12,  4, 26, 19,
         14, 26, 18,  0, 21,  4, 26,  8, 19],
        [ 8, 13,  2, 14, 12, 12, 14,  3,  8, 14, 20, 18, 26,  0, 18, 26,  7,  0,
         18, 26,  1,  4,  4, 13, 26, 18, 19,  0, 19,  4,  3, 26,  8, 13, 18,  4,
          2, 20, 17,  4, 26, 20, 13,  7,  4,  0, 11, 19,  7, 24, 26,  0, 13,  3,
         26, 20, 13, 15, 17, 14, 21,  8,  3,  4,  3, 26, 22,  8, 19,  7, 26, 19,
          7,  4, 26, 15, 17,  8, 13, 19,  4,  3, 26, 14, 17, 26, 22, 17,  8, 19,
         19,  4, 13, 26, 17,  4,  6, 20, 11,  0, 19,  8, 14, 13, 18, 26, 17,  4,
         16, 20,  8, 17,  4,  3, 26,  1, 24, 26, 11,  0, 22,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0],
        [19,  7, 20, 18, 26,  3,  8, 18, 15, 14, 18,  8, 13,  6, 26, 14,  5, 26,
         19,  7,  4, 26, 14,  1,  9,  4,  2, 19,  8, 14, 13, 26, 18, 14, 26, 11,
         14, 13,  6, 26, 17,  0,  8, 18,  4,  3, 26,  0,  6,  0,  8, 13, 18, 19,
         26, 19,  7,  4, 26,  8, 13,  3, 20, 18, 19, 17,  8,  0, 11, 26,  4, 12,
         15, 11, 14, 24, 12,  4, 13, 19, 26, 14,  5, 26, 15, 17,  8, 18, 14, 13,
          4, 17, 18, 26,  8, 13, 26, 13,  4, 22,  6,  0, 19,  4,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 11, 20, 13, 26,  8, 13, 26, 18,  7, 17, 14, 15, 18,  7,  8, 17,  4,
         26,  7,  0,  3, 26,  0, 26, 11, 14,  2, 10, 20, 15, 26, 20, 13,  3,  4,
         17, 26, 19,  7,  4, 26, 19, 14, 22, 13, 26,  7,  0, 11, 11,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0]])
tensor([[[1.6285e-05, 5.9003e-05, 1.1341e-04,  ..., 6.8129e-04,
          3.8052e-04, 9.5891e-05],
         [5.9954e-06, 7.2669e-05, 1.4392e-04,  ..., 1.0955e-03,
          9.5244e-04, 2.3319e-04],
         [7.4591e-06, 7.3114e-05, 1.4612e-04,  ..., 9.5778e-04,
          8.6950e-04, 2.3202e-04],
         ...,
         [2.5932e-05, 2.7131e-04, 8.4979e-04,  ..., 1.2802e-04,
          1.1631e-04, 7.0560e-06],
         [3.7444e-06, 6.8189e-05, 2.6175e-04,  ..., 5.3140e-06,
          2.6308e-06, 2.2163e-07],
         [3.7959e-06, 3.9087e-05, 7.3327e-05,  ..., 1.1121e-05,
          1.5125e-06, 2.0831e-07]],

        [[1.2612e-04, 2.7477e-04, 2.4952e-03,  ..., 1.3393e-05,
          4.3939e-05, 6.6732e-06],
         [4.7812e-04, 1.0743e-03, 1.1925e-02,  ..., 3.2139e-05,
          9.7591e-05, 1.5829e-05],
         [6.8355e-04, 2.0091e-03, 1.0325e-02,  ..., 5.0787e-05,
          1.2569e-04, 1.7642e-05],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[1.4511e-05, 3.1519e-04, 4.5528e-03,  ..., 3.1285e-04,
          1.1198e-04, 2.2458e-05],
         [3.3051e-05, 5.6563e-04, 9.7150e-03,  ..., 2.8503e-04,
          3.6504e-04, 6.9402e-05],
         [3.8245e-05, 2.6885e-04, 4.3670e-03,  ..., 1.2382e-04,
          1.5692e-04, 2.7356e-05],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[4.6964e-05, 6.5309e-04, 2.7690e-03,  ..., 5.0485e-04,
          7.3887e-04, 7.2745e-05],
         [8.8662e-05, 1.1942e-03, 6.0123e-03,  ..., 1.0887e-02,
          8.4339e-03, 8.8066e-04],
         [4.9725e-05, 2.2685e-04, 4.5390e-03,  ..., 1.8288e-02,
          1.0293e-02, 1.0156e-03],
         ...,
         [7.1152e-06, 3.9435e-05, 2.6830e-04,  ..., 1.7620e-06,
          8.1755e-07, 7.8368e-08],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]]) tensor([[ 8, 19, 26, 22,  0, 18, 26, 19,  7, 14, 20,  6,  7, 19, 26, 19,  7,  0,
         19, 26, 19,  7,  8, 18, 26, 22, 14, 20, 11,  3, 26,  6, 20,  0, 17,  0,
         13, 19,  4,  4, 26,  2, 14, 13, 18, 19,  0, 13, 19, 26, 18, 20, 15,  4,
         17, 21,  8, 18,  8, 14, 13, 26,  0, 13,  3, 26,  8, 13, 18, 15,  4,  2,
         19,  8, 14, 13, 26,  1, 20, 19, 26,  8, 19, 26,  3,  8,  3, 26, 13, 14,
         19,  7,  8, 13,  6, 26, 14,  5, 26, 19,  7,  4, 26, 10,  8, 13,  3, 26,
          0, 13,  3, 26, 14, 13, 11, 24, 26, 19,  7,  4, 26, 15, 17,  4, 18,  4,
         13,  2,  4, 26, 14,  5, 26, 22,  0, 17,  3,  4, 17, 18, 26, 14, 13, 26,
          3, 20, 19, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0],
        [ 1, 20, 19, 26,  8, 13,  3,  4,  4,  3, 26,  7,  8, 18, 26, 22,  7, 14,
         11,  4, 26, 17, 20, 11,  4, 26, 22,  0, 18, 26,  5,  0, 17, 26, 19, 14,
         14, 26, 12,  8, 11,  3, 26,  0, 13,  3, 26, 20, 13,  3,  4, 17, 26, 19,
          7,  8, 18, 26, 12,  8, 18, 19,  0, 10,  4, 13, 26, 11,  4, 13,  8,  4,
         13,  2, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0],
        [19,  7,  4, 26,  2, 17,  8, 12,  8, 13,  0, 11, 18, 26,  0, 17,  4, 26,
         13, 14, 19, 26,  4, 23, 15, 14, 18,  4,  3, 26, 19, 14, 26, 21,  8,  4,
         22, 26, 19,  8, 11, 11, 26, 19,  7,  4, 24, 26, 12, 14, 20, 13, 19, 26,
         19,  7,  4, 26,  5,  0, 19,  0, 11, 26, 18, 19,  0,  6,  4, 26, 19,  7,
          4, 26, 11,  0, 18, 19, 26, 15,  0, 17, 19, 26, 14,  5, 26, 19,  7,  4,
         26, 18, 19,  0,  6,  4, 26, 14, 17, 26, 19,  7,  0, 19, 26, 13,  4, 23,
         19, 26, 19, 14, 26, 19,  7,  4, 26,  9,  0,  8, 11,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0],

KeyboardInterrupt: